name: techcore
services:
  book-service:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: book-service
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - "./module_4:/app/module_4"
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis_db
      - mongo_db
      - rabbitmq
      - celery-worker
      - celery-beat
      - flower
      - zookeeper
      - kafka1
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    env_file:
      - ./.env
    depends_on:
      - book-service
    ports:
      - 8080:8080
    environment:
      - BOOK_SERVICE_URL=http://book-service:8000
      - PYTHONPATH=/app/module_11
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    restart: unless-stopped

  redis_db:
    image: redis:alpine
    container_name: redis_db
    ports:
      - 6379:6379
    env_file:
       - ./.env
    restart: unless-stopped

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    env_file:
       - ./.env
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    command: python -m celery -A module_4.app_celery.new_app_celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis_db
    volumes:
      - "./module_4:/app/module_4"
    working_dir: /app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0
      - PYTHONPATH=/app
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: module_4/app_celery/Dockerfile.schedule
    container_name: celery_beat
    command: python -m celery -A module_4.app_celery.new_app_celery beat --loglevel=info
    depends_on:
      - redis_db
      - rabbitmq
      - celery-worker
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0
    restart: unless-stopped
  
  flower:
    image: mher/flower:alpine
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: flower
    command: python -m celery -A module_4.app_celery.new_app_celery flower --port=5555
    ports:
      - '5555:5555'
    depends_on:
      - rabbitmq
      - redis_db
      - celery-worker
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0
    restart: unless-stopped
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper-data:/zookeeper_data
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    volumes:
      - kafka-data:/kafka_data
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
  
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    restart: unless-stopped
  
  analytics-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: python -m module_4.app_kafka.consumer
    depends_on:
      - kafka1
      - mongo_db
    environment:
      - PYTHONPATH=/app/module_4 
    restart: unless-stopped
  
  analytics-worker-async:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: python -m module_4.app_kafka.async_consumer
    depends_on:
      - kafka1
      - mongo_db
    environment:
      - PYTHONPATH=/app/module_4 
    restart: unless-stopped
  
  faust-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: python -m module_4.app_kafka.app_faust
    depends_on:
      - kafka1
    environment:
      - PYTHONPATH=/app/module_4
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
  mongodata:
    driver: local
  rabbitmq-data:
    driver: local
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
  
    