global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'book-service'
    static_configs:
      - targets: ['book-service:8000']
        labels:
          service: 'book-service'
          environment: 'development'
